import Head from 'next/head';
import Grid2 from '@mui/material/Unstable_Grid2'; // Grid version 2
import { MainLayout } from '@/layouts';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<MainLayout>
				<Grid2>index</Grid2>
			</MainLayout>
		</>
	);
}
